### ISSUE TITLE
OpenTelemetry-JS plugin

### ISSUE THREAD

**Issue by adamegyed** [mkinoshi/fastify-opentelemetry#5]
Hello,

I am a contributor to the OpenTelemetry JavaScript repository, and was looking to write a fastify plugin when I ran into this project. I see that this functions as a plugin to fastify that then interacts with OpenTelemetry. Would you be alright with me adapting this work to become a plugin for OpenTelemetry? You can view the currently supported OpenTelemetry JS plugins and how they work here: https://github.com/open-telemetry/opentelemetry-js-contrib

Thanks,
Adam

**Comment by mkinoshi** [comment]
Sorry I didn't realize this one, yeah for sure!
